type Passerelle {
    id: ID
    title: String
    description: String
    image: String
    geo: Geo
    favorites : [Profile]
    contributor: Profile
    validated: Boolean
    created_at: Date
    updated_ate: Date
}

type Query {
    passerelles(filter: FilterType): [Passerelle]
    findPasserelle(id: ID!): Passerelle
}

input FilterType {
  limit: Int
  order: FindOptionOrderValue 
}

enum FindOptionOrderValue {
  ASC
  DESC
}