type Passerelle {
    id: id
    title: String
    description: String
    image: String
    geo: Geo
    favorites : [Profile]
    contributor: Profile
    validated: Boolean
    created_at: Date
    updated_ate: Date
}